import 'package:flutter/material.dart';
import '../models/service_category.dart';
import '../models/service_provider_model.dart';
import '../models/service_request.dart';

class MockData {
  static List<ServiceCategory> categories = [
    const ServiceCategory(
      id: 'cat_electrician',
      name: 'Electrician',
      description: 'Wiring, fixtures, breaker panels, emergency repairs',
      icon: Icons.electrical_services_rounded,
      startingPrice: 45.0,
      popularTag: 'Most Requested',
      categoryColor: Color(0xFF6366F1),
    ),
    const ServiceCategory(
      id: 'cat_plumber',
      name: 'Plumbing',
      description: 'Leaks, pipe fitting, drain cleaning, water heaters',
      icon: Icons.plumbing_rounded,
      startingPrice: 50.0,
      popularTag: 'Top Rated',
      categoryColor: Color(0xFF0EA5E9),
    ),
    const ServiceCategory(
      id: 'cat_ac',
      name: 'AC Technician',
      description: 'HVAC repair, coolant refilling, duct cleaning',
      icon: Icons.ac_unit_rounded,
      startingPrice: 65.0,
      popularTag: 'Summer Hot',
      categoryColor: Color(0xFF06B6D4),
    ),
    const ServiceCategory(
      id: 'cat_carpenter',
      name: 'Carpentry',
      description: 'Furniture assembly, doors, cabinets, custom woodwork',
      icon: Icons.carpenter_rounded,
      startingPrice: 40.0,
      categoryColor: Color(0xFFD97706),
    ),
    const ServiceCategory(
      id: 'cat_appliance',
      name: 'Appliance Repair',
      description: 'Refrigerators, washing machines, microwaves, ovens',
      icon: Icons.kitchen_rounded,
      startingPrice: 55.0,
      categoryColor: Color(0xFF8B5CF6),
    ),
    const ServiceCategory(
      id: 'cat_painter',
      name: 'House Painting',
      description: 'Interior & exterior painting, wall touch-ups',
      icon: Icons.format_paint_rounded,
      startingPrice: 80.0,
      categoryColor: Color(0xFFEC4899),
    ),
  ];

  static List<ServiceProviderModel> providers = [
    ServiceProviderModel(
      id: 'prov_01',
      name: 'Alexander Wright',
      title: 'Master Electrician',
      categoryId: 'cat_electrician',
      rating: 4.9,
      completedJobs: 142,
      avatarUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&q=80&w=256',
      bio: 'Licensed electrician with 8+ years experience in residential wiring, smart home setups, and quick troubleshooting.',
      hourlyRate: 55.0,
      skills: ['Smart Switches', 'Breaker Box Upgrade', 'EV Charger Install', 'Rewiring'],
      isVerified: true,
      phone: '+1 555-0192',
      latitude: 37.7790,
      longitude: -122.4180,
    ),
    ServiceProviderModel(
      id: 'prov_02',
      name: 'Marcus Vance',
      title: 'Certified Plumbing Specialist',
      categoryId: 'cat_plumber',
      rating: 4.8,
      completedJobs: 189,
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=256',
      bio: 'Fast emergency plumbing repairs, water heater installation, leak detection, and pipe replacements.',
      hourlyRate: 60.0,
      skills: ['Leak Detection', 'Tankless Water Heater', 'Drain Unclogging', 'Pipe Fitting'],
      isVerified: true,
      phone: '+1 555-0184',
      latitude: 37.7720,
      longitude: -122.4230,
    ),
    ServiceProviderModel(
      id: 'prov_03',
      name: 'Elena Rostova',
      title: 'HVAC & Climate Control Pro',
      categoryId: 'cat_ac',
      rating: 4.95,
      completedJobs: 98,
      avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=256',
      bio: 'Expert AC repair technician specializing in split units, central HVAC systems, and eco-friendly gas refilling.',
      hourlyRate: 70.0,
      skills: ['Freon Gas Recharge', 'Compressor Repair', 'Thermostat Setup', 'Duct Sanitation'],
      isVerified: true,
      phone: '+1 555-0177',
      latitude: 37.7810,
      longitude: -122.4110,
    ),
  ];

  static List<ServiceRequest> initialRequests = [
    ServiceRequest(
      id: 'req_101',
      categoryId: 'cat_electrician',
      categoryName: 'Electrician',
      customerId: 'cust_01',
      customerName: 'Sarah Jenkins',
      customerPhone: '+1 555-0112',
      providerId: 'prov_01',
      providerName: 'Alexander Wright',
      providerPhone: '+1 555-0192',
      status: RequestStatus.inProgress,
      description: 'Living room light fixture flickering and main outlet sparks when plugging in vacuum.',
      photoUrls: ['https://images.unsplash.com/photo-1558402529-d2638a7023e9?auto=format&fit=crop&q=80&w=600'],
      latitude: 37.7749,
      longitude: -122.4194,
      address: '742 Market Street, San Francisco, CA',
      isUrgent: true,
      estimatedCost: 85.0,
      createdAt: DateTime.now().subtract(const Duration(minutes: 45)),
      providerLat: 37.7765,
      providerLng: -122.4175,
    ),
    ServiceRequest(
      id: 'req_102',
      categoryId: 'cat_plumber',
      categoryName: 'Plumbing',
      customerId: 'cust_02',
      customerName: 'David Miller',
      customerPhone: '+1 555-0144',
      status: RequestStatus.pending,
      description: 'Kitchen sink pipe leaking water onto floor underneath cabinet.',
      photoUrls: ['https://images.unsplash.com/photo-1585704032915-c3400ca199e7?auto=format&fit=crop&q=80&w=600'],
      latitude: 37.7820,
      longitude: -122.4250,
      address: '120 Valencia St, San Francisco, CA',
      isUrgent: false,
      estimatedCost: 65.0,
      createdAt: DateTime.now().subtract(const Duration(minutes: 15)),
    ),
  ];
}
